---
extends: default

skip_list:
  - meta-no-info
  - no-log-password

ignore: |
  LICENSE
  ansible.cfg
  **/templates/**/*.yml
  **/templates/**/*.yaml
  **/vault.yml

rules:
  line-length:
    level: warning
    max: 120
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  new-lines: disable
  truthy:
    allowed-values:
      - "true"
      - "false"
      - "on"
